version: '3.5'
services:
  react-app-web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - .:/app
  react-app-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
